### ISSUE TITLE
CImg: Build fails on git --archive (firewall issue?)

### ISSUE THREAD

**Issue by olear** [devernay/openfx-misc#25]
https://github.com/devernay/openfx-misc/blob/master/CImg/Makefile#L46

Build fails with "connection refused" if firewall blocks port 9418, I opened the port but now get:
```
make[1]: Entering directory `/root/natron-linux/tmp/openfx-misc/CImg'
git archive --remote=git://git.code.sf.net/p/gmic/source f99ec436e44134d4974340a862cdfb159b0961f5:src CImg.h | tar xf -
remote: fatal: Not a valid object name
remote: git upload-archive: archiver died with error
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

A submodule would maybe be a better solution?

**Comment by devernay** [comment]
You will get the same problem with a submodule if the git port is blocked.
and you probably don't want to pull out the whole gmic repository.

fred

**Comment by olear** [comment]
Works, thanks.
