### ISSUE TITLE
Display viewer issue with plasma 

### ISSUE THREAD

**Issue by rcspam** [devernay/openfx-misc#26]
Apparently a bug with plasma plugin:
See [Natron #638](https://github.com/MrKepzie/Natron/issues/638)

**Comment by olear** [comment]
Since Plasma now has seed, are there any value in the Texture plugin in Arena.ofx? I just added it for the seed. I don't want to add "duplicates"

**Comment by rcspam** [comment]
The problem always here with the last update snapshot (2015 05 31)

https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-05-31_13.36.44.mp4

**Comment by devernay** [comment]
yes, rendering is different for each renderscale, but render at scale=1 is always the same (see doc/tooltip). it's impossible to have the same aspect for all scales without disabling renderscale support.

Haven't tried the texture plugin in arena, but it probably has different kinds of noise.

**Comment by rcspam** [comment]
Yes i have tried it, I just wanted to report you this problem.
I had not see the doc/tooltip. Sorry.
Regards
