### ISSUE TITLE
How to build under Windows ?

### ISSUE THREAD

**Issue by YruamaLairba** [devernay/openfx-misc#27]
Hello, I'm unable to build under windows using the misc.vcxproj. I have missing file or missing ID. I already put the openfx folder ( from MrKepzie/openfx) in this directory, but it's not enougth.

**Comment by MrKepzie** [comment]
You have to type:
    git submodule update -i --recursive

After cloning. It will fetch proper dependencies

**Comment by YruamaLairba** [comment]
Ok, It solved the dependencies issue, but I get many error with "min" and "max". I tried to remove the "NOMINMAX" macro but i just get other errors. I just discovered the issue about WinDef.h of MSVC

**Comment by MrKepzie** [comment]
Which version of MSVC are you using ?

**Comment by YruamaLairba** [comment]
I use Microsoft Visual Studio Express 2013 for windows Desktop

**Comment by MrKepzie** [comment]
We do not officially build Natron on visual 2013, we are using visual 2010. You could try submitting a patch to fix compile errors  if you wish

**Comment by YruamaLairba** [comment]
ok, i found a proper way to fix it. According to the standard, "min" and "max" belong to the algorithm lib. So you need to include this lib each time you use min or max.
Source http://www.cplusplus.com/reference/algorithm/max/

**Comment by MrKepzie** [comment]
If you want to submit a pull request with the fix we would appreciate. I'm closing this.
