### ISSUE TITLE
Support OFX 1.4 render quality

### ISSUE THREAD

**Issue by devernay** [devernay/openfx-misc#30]
See http://openeffects.org/standard_changes/render-quality
Some plugins have to be changed, such as Transform (full quality > super sampling disabled>impulse filter)
See also issue MrKepzie/Natron#780

**Comment by manuelsongokuh** [comment]
hello
sorry if i ask you:
when will full supported OFX 1.5?or any information for roadmap future..?

**Comment by devernay** [comment]
closed by https://github.com/devernay/openfx-misc/commit/ad483d9b796c1f3fd65c1de3d54dcf2f3299d1f3
