### ISSUE TITLE
Add New Layer/Plane OFX plugin (question)

### ISSUE THREAD

**Issue by mccartnm** [devernay/openfx-misc#39]
I'm looking to, in both Nuke and Natron, have the plugin create a new layer and modify certain channels as it renders. Much like a Shuffle it will take some channels and pass them into our new layer while generating others based off of Int/Color params but the idea would be to auto-generate a new plane to work with and set it's initial data to be used down stream, committing it to the output. I have the render math but not the new layer to work with.

So far I have a heavily modified Shuffle that's not quite giving me the right params in either app so I'm working on that. I've looked into the `makeNatronCustomChannel()` as well as run through the `ReadOIIO` a few times but am having difficulty understanding just what the string syntax/layout should be for generating a new layer in the app.

When would be the best time to create the channel as well? As far I can tell from `ReadOIIO` it's on the file being changed which makes sense but I'm looking to just have it start with that layer made by the plugin.

Any info/questions/feedback is greatly appreciated!
Cheers, 
Michael McCartney

**Comment by MrKepzie** [comment]
I recently revamped how we write multi-plane plug-ins in Natron.
I have detailed how it works in here: https://github.com/devernay/openfx/blob/e0043853601b6369f1b2fe1894c49c1f522d6ff0/include/ofxNatron.h#L61

Nuke is limiting multi-plane to Motion Vectors and Disparity for OpenFX. Natron makes all planes available, as explained in the comments. 

Everything you describe is achievable with Natron, but Nuke does not support it. 

You would need to use the extensions provided in ofxsMultiPlane.cpp (in SupportExt) as done in Shuffle and inherit the MultiPlaneEffect which enables you to create layers and channel selectors easily. 

For reference, look at the Shuffle code or Distortion plug-in which use it.  

To advertise about available layers, the plug-ins does so in getClipComponents()

**Comment by mccartnm** [comment]
Awesome!
Thanks for the info and quick response. Those notes have already proved extremely useful.

Perhaps, while it's not the most logical, I could ride the Disparity planes while in Nuke. I need two planes in the long run so the Left/Right could work. However aren't they limited to 2 channels (x, y) each? I will need all 4.

Glad Natron can at least handle this so my development can move forward. I'll see about at least creating an NDK node to parallel whatever I make work in Natron so support is there for both.

For the rendering process itself I am looking to assign an ID to one channel of the layer. (every pixel of that channel would equal that number). Something like...
```cpp
/// Objects defined in base to use/set. Sampled from Shuffle.
// BitDepth must be eBitDepthFloat and Components must 4
int _id_channel;
float _id;
std::vector<InputPlaneChannel> _inputPlanes;
// ...

//...
// process pixels to new layer. Layer is made by the plugin on the
// getClipComponents() call using the Utils::makeNatronCustomChannel()
// and adding the component via clipComponents.addClipComponents()
void multiThreadProcessImages(OfxRectI procWindow)
{
    assert(_inputPlanes.size() == 4);

    // component by component rendering a-la Shuffle
    for ( int c = 0; c < 4; ++c ) {
        
        // We're always pulling from the RGB(+-)A to pass into our new layer.
        // The image for this plane set in the setupAndProcess()
        const OFX::Image* srcImg = _inputPlanes[c].img;

        // The channel index for this plane is set via the setupAndProcess()
        // as well. This builds off of the Channel Params which could be
        // hidden from the user and "hardcoded" to force to the proper
        // output layer.
        int srcComp = _inputPlanes[c].channelIndex;
        // .. fillzero check

        for ( y = procWindow.y1; y < procWindow.y2; y++ ) {
            // ... effect abort check

            // Writing to pixels found in getPlaneNeededInOutput()
            // that get parsed properly from _outputLayer Param choice.
            DSTPIX *dstPix = (DSTPIX *) _dstImg->getPixelAddress(procWindow.x1, y);

            for ( x = procWindow.x1; x < procWindow.x2; x++ ) {
                // Here we check to see if the component we are on is meant to
                // be our ID.
                if ( c == _id_channel ) { // id_channel set to 2 (green in term of Natron viewer)
                    dstPix[c] = _id; // range from 1-65536. Could do more checking here.
                } else {
                    // Otherwise we just push the source RGB(+-)A to our new Layer.
                    PIXSRC *srcPIX = (PIXSRC *) (srcImg ? srcImg->getPixelAddress(x, y) : 0)
                    dstPix[c] = srcImg ? srcPix : 0.0f;
                }
                dstPix += nComponentsDst; // Leap to the same component on the next pixel.
            }
        }
    }
}
//...
```
Seems like it would work. It's extremely similar to the Shuffle render process minus the _id slot. Even if I add a mask I would push it to the 3rd slot (leave the alpha still passing through) It's for a bigger development project but I like what kind of doors it opens.

I would be thrilled to hear any other comments you might have. Thanks again.
Cheers!

**Comment by MrKepzie** [comment]
For Nuke support, I would recommend using the NDK as they offer much more than they do via OpenFX.
I do advise against using multi-plane in OpenFX for Nuke because it is very clumsy how they do it for The Furnace plug-ins: you have to tell in getClipPreferences whether you need motion vectors/disparity XY and then it will you to render both planes in the same render action.

Our solution offers truly arbitrary planes to be processed/passed through. I will also submit it to the OpenFX association standard once it is polished. We still have a few things we want to add, such as:

- Better integration between Factory/Plug-in class: everything done in the plug-in expects that you correctly called the function in the factory. There should be a single call instead.

- Maybe some basic examples showing how multi-layers work

**Comment by mccartnm** [comment]
Perfect. I'm excited for all of that. A lot of stellar image manipulation can happen when we can work with an 'n' number of planes. Especially when it comes to non-nodal NLE's (ie Davinci, Quantel). I've been looking for OFX to really support multi planar images for a while. It would be a great evolution in the API. I will be happy to share any of my findings/experiments as well.
