### ISSUE TITLE
build fail on linux ( fatal error: GL/gl.h no such file)

### ISSUE THREAD

**Issue by nicholascarroll** [devernay/openfx-misc#40]
Failing to build with 'make' on linux,getting this error:
ColorLookup.cpp:35:19: fatal error: GL/gl.h: No such file
[openfx-misc-build-fail.txt](https://github.com/devernay/openfx-misc/files/233782/openfx-misc-build-fail.txt)

**Comment by devernay** [comment]
You probably miss a package.

If on Debian, Mint or Ubuntu, type:
```
apt-file search "gl.h"
```
Then, you'll find out the package where the file is, and install it, as in
```
sudo apt-get install libmesa-dev
```

Note that a good way to install all opengl development files is to install the development package for GLEW (look for it in your package manager)

**Comment by devernay** [comment]
```
apt-file search GL/glew.h
sudo apt-get install libglew-dev
```

**Comment by nicholascarroll** [comment]
Thanks, I did it using the package manager.
