### ISSUE TITLE
Natron 2.2.5 doesn't load new OFX-misc Plugins

### ISSUE THREAD

**Issue by SebastianBugna** [devernay/openfx-misc#48]
Hi,
I'm not being able to load custom OFX plugins in Natron based on the openfx-misc plugins.
In previous releases I could manage to do this several times without problems.
I use Ubuntu command line, with GNU Make 4.1, and Natron 2.2.5

 I made a clean test:

git clone https://github.com/devernay/openfx-misc.git
cd openfx-misc
git submodule update -i -r

I rename Invert folder to ¨CustomPlugin¨, renamed also within the makefile, and CustomPlugin.cpp.
In the code just changed the Grouping and Identifier lines , to load the plugin in a new group called ¨CustomPlugin¨:

#define kPluginName "CustomPlugin"
#define kPluginGrouping "NewGroup"
#define kPluginDescription "Load OFX plugin"
#define kPluginIdentifier "net.sf.openfx.CustomPlugin"

I´m building the plugins from linux terminal> make CONFIG=release BITS=64 
In Natron, in Preferences/Plugins I added the path to the created folder Linux-64-release .

The last days i´ve been trying to do this in many different ways, but Natron doesn´t load the new plugin in a new group.
Previous releases didn't show this issue.

**Comment by MrKepzie** [comment]
use strace when launching Natron to figure out why your plug-in is not loaded. It's probably because of a shared library.

**Comment by devernay** [comment]
If Natron doesn't crash, that's certainly not a library issue.
if you copy your .ofx.bundle to /usr/OFX/Plugins, does it work?

**Comment by SebastianBugna** [comment]
Thanks.
 copying the.ofx.bundle to /usr/OFX/Plugins works fine!

Anyway I still would like to load directly from the building directory.

**Comment by SebastianBugna** [comment]
Could you detect the issue? 
Im building in the /usr/OFX/Plugins now, but it's unconfortable copying the bundles each time I build a test.

Thanks in advance.

**Comment by devernay** [comment]
you can also put symbolic links in /usr/OFX/Plugins, that's how I work.
This is a Natron issue, can you please post an issue in the Natron github? Thanks
In the issue, also give the Natron output you see in the terminal.
Closing the openfx-misc issue, since it's not an openfx-misc issue
